// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Graphql = require("graphql");

function create(query, mutation, _) {
  return new Graphql.GraphQLSchema({
              query: query,
              mutation: mutation
            });
}

exports.create = create;
/* graphql Not a pure module */
