// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Schema  = require("../src/schema.js");
var Graphql = require("graphql");

Schema.create(new Graphql.GraphQLObjectType(), /* None */0, /* () */0);

/*  Not a pure module */
